name: Create an comment on new issues

on:
  issues:
    types: [closed]

jobs:
  comment-with-action:
    runs-on: unbuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{toJSON(github.event) }}' | jq
        shell: bash


