name: Deploy Ngnix

on:
  push:
    branches: 
    - 'main'
env:
  PROJECT_ID: 'autopilot-cluster-1'
  PROJECT_NUMBER: '1034414536999'

  CLUSTER: 'gke-opt-demo'
  REGION: 'us-central1'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: 'code checkout'
      uses: 'actions/checkout@v4'
    #
    # Authenticate to Google Cloud using workload identity federation
    #
    - name: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc'
        service_account: 'github-actions-workflow@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

    - id: 'Connect to GKE'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ env.CLUSTER }}
        location: ${{ env.REGION }}

    # The KUBECONFIG env var is automatically exported and picked up by kubectl.
    - id: 'get-pods'
      run: 'kubectl get pods'
