name: Create a comment on PR

on:
  issues:
    types: [opened]

jobs:
  commment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
        
      - name: Create comment with API
        run: |
          gh api -X POST \
            http://api.github.com/repos/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/issues/${{ github.event.issue.number }}/comments \
            -f body='
            Comment from API
            ' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
