name: Create a comment on PR

on:
  issues:
    types: [opened]

jobs:
  commment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
          gh api \
          --method POST \
          /repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body='Me too' 
        #env:
          #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
