name: Create a comment on PR

on:
  pull_request:
    types: [opened, reopened]
    #paths:
     # - '**.yaml'

jobs:
  commment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
          gh api \
          --method POST \
          /repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body='Me too' 
