name: Create a comment on PR

on:
  issues:
    types: [opened]

jobs:
  commment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
        
      - name: Create comment with API
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/aburhan/${{ github.event.repository.name }}/issues/${{ github.event.issue.number }}/comments \
          -f body='Me too' 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
