name: k8s Workload Rightsizing Review Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
        
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Leave a review on the PR
      uses: actions/github-script@v7
      with:
        script: |
          const pullRequestNumber = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const body = 'Thank you for your contribution! We are reviewing it.';
          const event = 'COMMENT'; // Other options: APPROVE, REQUEST_CHANGES
          await github.rest.pulls.createReview({
            owner,
            repo,
            pull_number: pullRequestNumber,
            body,
            event,
          });
        github-token: ${{secrets.GITHUB_TOKEN}}
