name: K8s Workload Rightsizing Review Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Dump github context
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Request Changes
      uses: actions/github-script@v7
      with:
        script: |
          const pullRequestNumber = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const message = 'Workload rightsizing issue please correct'
          const event = 'REQUEST_CHANGES';
          await github.rest.pulls.createReview({
            owner,
            repo,
            pull_number: pullRequestNumber,
            body,
            event,
          });
        github-token: ${{secrets.GITHUB_TOKEN}}
