name: Transform File and Create PR

on:
  workflow_dispatch:

env:
  PROJECT_ID: 'gke-opt-demo'
  PROJECT_NUMBER: '1034414536999'

  CLUSTER: 'online-boutique'
  LOCATION: 'us-central1-f'
  
jobs:
  transform-and-create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      #- name: Transform file
      #  run: python my_script.py
      
      - name: Install dependencies (if any)
        run: |
          pip install -r requirements.txt

      - name: Transform file
        run: python .app//transformation_script.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Apply transformation to file" || echo "No changes to commit"
          git push origin HEAD:new-branch  # Push changes to a new branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: new-branch  # The branch where changes are committed
          title: "Transformed File PR"
          body: "This PR includes changes made by the transformation script."
          labels: automated-pr  # Add labels as needed

